---
- hosts: 127.0.0.1
  connection: local

  roles:
    - { role: brew-pkgs-and-apps }
    - { role: powerline-fonts, become: yes }
    - { role: config-zsh, become: yes }
    - { role: config-iterm2, become: yes }
    - { role: config-sublime3, become: yes }
