---
  homebrew_installed_packages:
    - wget
    - tree
    - mysql
    - python3
    - pyenv
    - node
    - zsh
    - zsh-completions
    - vim
    - homebrew/fuse/ntfs-3g

  homebrew_upgrade_all_packages: no

  homebrew_taps:
    - homebrew/core
    - caskroom/cask

  homebrew_cask_apps:
    - firefox
    - google-chrome
    - iterm2
    - slack
    # sublime text 3 by default
    - sublime-text
    - grammarly
    - the-unarchiver
    # java 8
    - java
    - docker
    - virtualbox
    - vagrant
    - vagrant-manager
    - evernote
    - texmaker
    - qlmarkdown
    - quicklook-json
    - osxfuse
    - pycharm

  homebrew_cask_appdir: /Applications
