---
  homebrew_installed_packages:
    - wget
    - tree
    - mysql
    - python3
    - pyenv
    - node
    - zsh
    - zsh-completions
    - vim
    - ntfs-3g # require osxfuse installed

  homebrew_upgrade_all_packages: no

  homebrew_taps:
    - homebrew/core
    - caskroom/cask
    - homebrew/fuse

  homebrew_cask_apps:
    - firefox
    - google-chrome
    - iterm2
    - slack
    # sublime text 3 by default
    - sublime-text
    - the-unarchiver
    # java 8
    - java
    - docker
    - virtualbox
    - vagrant
    - vagrant-manager
    - evernote
    - alfred
    - caffeine
    - texmaker
    - quicklook-json
    - pycharm
    # ocassionaly failed
    - grammarly
    - osxfuse # require to restart system after installation to take effect
    - qlmarkdown

  homebrew_cask_appdir: /Applications
